# Generated by Django 4.0 on 2022-02-08 12:33

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_product_costs_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='basis',
            field=models.CharField(choices=[('g', 'One Gram'), ('oz', 'One Troy Ounce'), ('kg', 'One Kilogram')], max_length=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='data',
            field=models.JSONField(default=gallery.models.my_default, null=True, verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.JSONField(default=gallery.models.my_default, null=True, verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='data',
            field=models.JSONField(default=gallery.models.my_default, null=True, verbose_name='Extra Data'),
        ),
    ]
